export const projectContexts = { enterprise: "Entreprise", academic: "Académique", personal: "Personnel" };

// Only confirmed information. Dates, results and external links stay absent until supplied.
// cover: null is an intentional placeholder, not a missing file or a fabricated screenshot.
const media = (folder, needed) => ({ cover: null, alt: needed, expectedPath: `/images/projects/${folder}/cover.png`, needed, gallery: [] });

export const projects = [
  {
    id: "iso50001", slug: "iso-50001", title: "ISO 50001", subtitle: "Pilotage énergétique industriel", context: "enterprise", tier: "featured", company: "Brasserie Champigneulles", date: null,
    summary: "Collecter, centraliser et visualiser les consommations énergétiques de l’usine dans une solution interne.",
    role: "Conception, développement, intégration et architecture de données, en collaboration avec les services de l’usine.",
    technologies: ["C#", "ASP.NET", "SQL Server", "OPC UA", "Power BI", "n8n"],
    images: media("iso50001", "Vue d’ensemble anonymisée du tableau de bord énergétique ISO 50001."),
    sections: [
      { title: "Contexte", text: "Le suivi énergétique reposait davantage sur une prestation externe. Le projet vise à construire une solution interne à la Brasserie Champigneulles." },
      { title: "Problématique", text: "Internaliser la collecte et l’exploitation des données énergétiques pour réunir leur traitement et leur visualisation." },
      { title: "Mon rôle", text: "Conception et développement d’une partie importante de la solution : intégration, architecture de données et échanges avec plusieurs services et représentants de l’usine." },
      { title: "Solution", text: "Collecte depuis les automates et serveurs OPC UA, intégration avec C# et ASP.NET, centralisation dans SQL Server et exploitation dans Power BI. n8n automatise les appels API et les remontées de données selon les flux." },
    ],
  },
  { id: "cicd", slug: "environnement-cicd", title: "Environnement CI/CD", subtitle: "Préparer, tester, déployer", context: "enterprise", tier: "selection", company: "Brasserie Champigneulles", summary: "Un environnement interne pour versionner les applications et préparer leurs tests et leur déploiement.", technologies: ["Docker", "Git", "Gitea"], images: media("cicd", "Schéma réel anonymisé de l’environnement : Gitea, BCApi, conteneurs et base de test, sans adresses ni noms de serveurs."), sections: [{ title: "Environnement", text: "Dépôts internes sur Gitea, versionnement Git et environnement Docker. Une copie conteneurisée des données sert aux tests de BCApi et à la préparation du déploiement." }] },
  { id: "kpi", slug: "securisation-kpi", title: "Applications KPI", subtitle: "Architecture & sécurisation", context: "enterprise", tier: "selection", company: "Brasserie Champigneulles", summary: "Conteneurisation et sécurisation des communications entre les services des applications KPI internes.", technologies: ["Docker", "Reverse proxy", "Step-CA", "HTTPS"], images: media("kpi", "Schéma réel anonymisé des services KPI, du reverse proxy et de Step-CA, sans IP, domaines internes ni secrets."), sections: [{ title: "Solution", text: "Services conteneurisés avec Docker, communications HTTPS via un reverse proxy et gestion des certificats avec Step-CA." }] },
  { id: "koragence", slug: "koragence", title: "Koragence", subtitle: "Site vitrine & plateforme B2B", context: "personal", tier: "selection", confidential: true, summary: "Participation au développement d’un site vitrine B2B et d’une plateforme métier dont une partie est confidentielle.", technologies: ["React"], images: media("koragence", "Capture de la page d’accueil publique du site vitrine Koragence, sans interface de la plateforme confidentielle."), sections: [{ title: "Contribution", text: "Participation au développement du site vitrine et de la plateforme métier B2B. Les fonctionnalités et les interfaces confidentielles ne sont pas présentées ici." }] },
  { id: "witch", slug: "witch-or-ghost", title: "Witch or Ghost", subtitle: "Game Jam · jeu 2D", context: "academic", tier: "selection", summary: "Un jeu développé en équipe autour d’une mécanique vivant / fantôme, entre labyrinthes et énigmes.", technologies: ["Python", "Pygame"], images: media("witch-or-ghost", "Capture en jeu montrant un labyrinthe et le personnage, idéalement avec la mécanique fantôme visible."), sections: [{ title: "Gameplay", text: "Gameplay 2D avec collisions, mode fantôme, énigmes, clés et potions. Le jeu est développé en équipe avec Python et Pygame." }] },
  { id: "freinte", slug: "rapport-freinte", title: "Rapport Freinte", subtitle: "Reporting industriel", context: "enterprise", tier: "selection", company: "Brasserie Champigneulles", summary: "Suivi de la freinte et analyse temporelle des données de production avec Power BI et SQL Server.", technologies: ["Power BI", "SQL Server"], images: media("freinte", "Capture anonymisée du rapport Power BI Freinte avec ses visualisations et filtres temporels."), sections: [{ title: "Reporting", text: "Exploitation de données de production dans Power BI : calcul et suivi de freinte, mesures et analyses temporelles à partir de SQL Server." }] },
  { id: "portfolio", slug: "portfolio", title: "Portfolio", subtitle: "Une identité spatiale interactive", context: "personal", tier: "selection", summary: "Conception et développement de ce portfolio interactif, du parcours aux preuves d’utilisation des technologies.", technologies: ["Next.js", "React", "CSS Modules", "Motion", "GSAP"], images: { ...media("portfolio", "Capture réelle de la page d’accueil du portfolio sur ordinateur."), cover: "/images/projects/portfolio/cover.png", alt: "Page d’accueil du portfolio de Kadir Ersoy, portrait et présentation sur fond spatial." }, sections: [{ title: "Conception", text: "Une interface responsive organisée autour du parcours, des compétences et des projets, avec des animations Motion et GSAP et des styles en CSS Modules." }] },
  { id: "traffic", slug: "simulation-trafic", title: "Simulation de trafic quotidien", context: "academic", tier: "archive", summary: "Modélisation de comportements de trafic avec des machines à états.", technologies: ["Python"], images: media("traffic-simulation", "Capture de la simulation en fonctionnement avec les véhicules et leurs états visibles."), sections: [] },
  { id: "invaders", slug: "space-invaders", title: "Space Invaders", context: "academic", tier: "archive", summary: "Développement académique d’un jeu en C#.", technologies: ["C#"], images: media("space-invaders", "Capture réelle d’une partie de Space Invaders."), sections: [] },
  { id: "unity", slug: "projet-unity", title: "Projet Unity", context: "academic", tier: "archive", summary: "Projet académique développé avec Unity et C#.", technologies: ["Unity", "C#"], images: media("unity", "Capture de la vue Game du projet Unity, distinct du projet Space Invaders."), sections: [] },
  { id: "evalbot", slug: "evalbot", title: "EvalBot", context: "academic", tier: "archive", summary: "Projet académique réalisé en assembleur.", technologies: ["Assembleur"], images: media("evalbot", "Photo réelle de l’EvalBot utilisé pour le projet ou capture de son environnement de développement."), sections: [] },
  { id: "data", slug: "projet-data", title: "Projet Data", context: "academic", tier: "archive", summary: "Projet académique de traitement de données avec Python.", technologies: ["Python"], images: media("data", "Capture réelle d’un notebook ou d’une visualisation du projet Data ; sujet et jeu de données à préciser."), sections: [] },
];

export const getProjects = context => projects.filter(project => context === "all" || project.context === context);
